services:
  collector:
    build:
      context: ../src/collector
      dockerfile: Dockerfile
    ports:
      - ${COLLECTOR_PORT:?error}:${COLLECTOR_PORT:?error}
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      APP_ADDR: ${COLLECTOR_ADDR:?error}
      KAFKA_ADDR: ${KAFKA_ADDR:?error}
      KAFKA_TOPIC: ${KAFKA_TOPIC:?error}
      VERBOSE: ${VERBOSE:?error}
      ENV: ${ENV:?error}
