name: clickstream

services:
  collector:
    build:
      context: ../src/collector
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - app-tier
    depends_on:
      - kafka
    environment:
      APP_ADDR: ${APP_ADDR}
      KAFKA_ADDR: ${KAFKA_ADDR}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      VERBOSE: ${VERBOSE}
      ENV: ${ENV}
